name: "Infrastructure"

volumes:
  user-service-postgres-volume:

services:
  user-service-postgres-db:
    image: postgres:17-alpine
    container_name: user-service-postgres-db

    environment:
      - POSTGRES_USER=${USER_MICROSERVICE_POSTGRES_USER}
      - POSTGRES_PASSWORD=${USER_MICROSERVICE_POSTGRES_PASSWORD}
      - POSTGRES_DB=${USER_MICROSERVICE_POSTGRES_DB}
      - PGPORT=${USER_MICROSERVICE_POSTGRES_PORT}

    command: "-p ${USER_MICROSERVICE_POSTGRES_PORT}"

    ports:
      - "${USER_MICROSERVICE_POSTGRES_PORT}:${USER_MICROSERVICE_POSTGRES_PORT}"

    volumes:
      - user-service-postgres-volume:/var/lib/postgresql/data

    healthcheck:
      test: >
        "bash -c pg_isready -U $${USER_MICROSERVICE_POSTGRES_USER} -d $${USER_MICROSERVICE_POSTGRES_PASSWORD} && 
                 psql -U $${USER_MICROSERVICE_POSTGRES_USER} -d $${USER_MICROSERVICE_POSTGRES_PASSWORD} -c 'SELECT 1'"
      interval: 10s
      timeout: 5s
      retries: 5

    deploy:
      resources:
        limits:
          memory: 512m

        reservations:
          memory: 256M

    networks:
      - carhunters_network

networks:
  carhunters_network:
    driver: bridge
    name: carhunters_network
