spring:
  output:
    ansi:
      enabled: ALWAYS

  cloud:
    config:
      override-system-properties: false

eureka:
  instance:
    hostname: ${HOSTNAME:localhost}
  client:
    service-url:
      defaultZone: http://${DISCOVERY_SERVICE_INSTANCE:localhost}:8761/eureka

management:
  endpoints:
    web:
      exposure:
        include: '*'

  info:
    git:
      mode: full

server:
  shutdown: graceful